/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tournamentorganizer;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Jessica &Christopher
 */
public class RoundInterface extends javax.swing.JFrame {
Timer myTimer = new Timer();
    public static char[] myPassword;

    /**
     * Creates new form RoundInterface
     */
    public RoundInterface() {
        initComponents();
        myTimer.scheduleAtFixedRate(update,0, 100);
        GetPassword.main();
    }
    private TimerTask update = new TimerTask() {

    @Override
    public void run() {
      changePairingsView();
    }
};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GiveResultsButton = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Table1Favored = new javax.swing.JLabel();
        Table1Unfavored = new javax.swing.JLabel();
        Table2Favored = new javax.swing.JLabel();
        Table2Unfavored = new javax.swing.JLabel();
        Table3Favored = new javax.swing.JLabel();
        Table3Unfavored = new javax.swing.JLabel();
        Table4Favored = new javax.swing.JLabel();
        Table4Unfavored = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GiveResultsButton.setText("Give Results");
        GiveResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GiveResultsButtonMouseClicked(evt);
            }
        });

        Table1Favored.setText("jLabel1");

        Table1Unfavored.setText("jLabel2");

        Table2Favored.setText("jLabel3");

        Table2Unfavored.setText("jLabel4");

        Table3Favored.setText("jLabel5");

        Table3Unfavored.setText("jLabel6");

        Table4Favored.setText("jLabel7");

        Table4Unfavored.setText("jLabel8");

        jButton1.setText("Change Names");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(GiveResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Table2Favored)
                    .addComponent(Table1Favored)
                    .addComponent(Table3Favored)
                    .addComponent(Table4Favored))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Table1Unfavored)
                    .addComponent(Table2Unfavored)
                    .addComponent(Table3Unfavored)
                    .addComponent(Table4Unfavored))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GiveResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table1Favored)
                            .addComponent(Table1Unfavored))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table2Favored)
                            .addComponent(Table2Unfavored))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table3Favored)
                            .addComponent(Table3Unfavored))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Table4Favored)
                            .addComponent(Table4Unfavored))))
                .addGap(18, 18, 18)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       getName.main();
    }//GEN-LAST:event_jButton1MouseClicked

    private void GiveResultsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiveResultsButtonMouseClicked
   boolean a = true;
   for (int i = 0; i<myPassword.length && a;i++){
       a = Password.getPassword()[i] == myPassword[i];
   }
   
        if(a) {
            System.out.println("password was correct");
           GetResults.main();
                
        } else {
        System.out.println("password was not correct");
        }
        
    }//GEN-LAST:event_GiveResultsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoundInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoundInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoundInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoundInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("started round interface runnable");
                TournamentOrganizer.configurePairings();
                System.out.println("finished configuring pairings");
                new RoundInterface().setVisible(true);
            }
        });
    }
    private void changePairingsView() {
        Table1Favored.setText(TournamentOrganizer.myTables[0].player1.getName());
        Table1Unfavored.setText(TournamentOrganizer.myTables[0].player2.getName());
        Table2Favored.setText(TournamentOrganizer.myTables[1].player1.getName());
        Table2Unfavored.setText(TournamentOrganizer.myTables[1].player2.getName());
        Table3Favored.setText(TournamentOrganizer.myTables[2].player1.getName());
        Table3Unfavored.setText(TournamentOrganizer.myTables[2].player2.getName());
        Table4Favored.setText(TournamentOrganizer.myTables[3].player1.getName());
        Table4Unfavored.setText(TournamentOrganizer.myTables[3].player2.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GiveResultsButton;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Table1Favored;
    private javax.swing.JLabel Table1Unfavored;
    private javax.swing.JLabel Table2Favored;
    private javax.swing.JLabel Table2Unfavored;
    private javax.swing.JLabel Table3Favored;
    private javax.swing.JLabel Table3Unfavored;
    private javax.swing.JLabel Table4Favored;
    private javax.swing.JLabel Table4Unfavored;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
